var annotated_dup =
[
    [ "AbstractStageFactory", "class_abstract_stage_factory.html", "class_abstract_stage_factory" ],
    [ "AddBallCommand", "class_add_ball_command.html", "class_add_ball_command" ],
    [ "Ball", "class_ball.html", "class_ball" ],
    [ "BallDecorator", "class_ball_decorator.html", "class_ball_decorator" ],
    [ "BallSmashDecorator", "class_ball_smash_decorator.html", "class_ball_smash_decorator" ],
    [ "BallSparkleDecorator", "class_ball_sparkle_decorator.html", "class_ball_sparkle_decorator" ],
    [ "Command", "class_command.html", "class_command" ],
    [ "CompositeBall", "class_composite_ball.html", "class_composite_ball" ],
    [ "CueBall", "class_cue_ball.html", "class_cue_ball" ],
    [ "Dialog", "class_dialog.html", "class_dialog" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameBuilder", "class_game_builder.html", "class_game_builder" ],
    [ "GameDirector", "class_game_director.html", "class_game_director" ],
    [ "GameStateCaretaker", "class_game_state_caretaker.html", "class_game_state_caretaker" ],
    [ "GameStateMemento", "class_game_state_memento.html", "class_game_state_memento" ],
    [ "Invoker", "class_invoker.html", "class_invoker" ],
    [ "Pocket", "class_pocket.html", "class_pocket" ],
    [ "ReplaceCueBallCommand", "class_replace_cue_ball_command.html", "class_replace_cue_ball_command" ],
    [ "StageOneBall", "class_stage_one_ball.html", "class_stage_one_ball" ],
    [ "StageOneBuilder", "class_stage_one_builder.html", "class_stage_one_builder" ],
    [ "StageOneFactory", "class_stage_one_factory.html", "class_stage_one_factory" ],
    [ "StageOneTable", "class_stage_one_table.html", "class_stage_one_table" ],
    [ "StageTwoBuilder", "class_stage_two_builder.html", "class_stage_two_builder" ],
    [ "StageTwoFactory", "class_stage_two_factory.html", "class_stage_two_factory" ],
    [ "StageTwoTable", "class_stage_two_table.html", "class_stage_two_table" ],
    [ "Table", "class_table.html", "class_table" ]
];